// <auto-generated />
namespace Coursework_WinForm_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ADDUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "202009111831594_ADDUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
