// <auto-generated />
namespace Coursework_WinForm_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ADDUserScore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDUserScore));
        
        string IMigrationMetadata.Id
        {
            get { return "202009120712224_ADDUserScore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
